# elasticsearch/Dockerfile
# Elasticsearch with Korean Jaso Analyzer
FROM docker.elastic.co/elasticsearch/elasticsearch:8.6.2

RUN bin/elasticsearch-plugin install https://github.com/netcrazy/elasticsearch-jaso-analyzer/releases/download/v8.6.2/jaso-analyzer-plugin-8.6.2-plugin.zip